### ISSUE TITLE
Dark Sky no longer issuing API Access Keys :)

### ISSUE THREAD

**Issue by paolosalvatori** [benc-uk/vuego-demoapp#25]
Hi Ben

Nice demo :) https://blog.darksky.net/ no longer accepts new sign ups :) I created an IPSTACK_API_KEY setting in my App Service for Linux  and entered my API access key but when I click Weather I see this message:

There was a problem 😥
Error: Status: error: 'Feature disabled, WEATHER_API_KEY is not set ',

Ciao
Paolo

**Comment by benc-uk** [comment]
Thanks for letting me know, I had a feeling this would happen after Apple bought them 😡 

I don't know when I'll get round to it, but I'll look to replacing the API with a different provider

**Comment by open-meteo** [comment]
Hi, creator of open-meteo here

I created a free no-api-key non-commercial API for that. Let me know, if I can help.

Best, Jeff

**Comment by paolosalvatori** [comment]
Thanks Jeff!

**Comment by benc-uk** [comment]
I've overhauled the app, and removed DarkSky and replaced it with OpenWeather API in v3.0.0
